SET NAMES utf8mb4;
-- T8 AI 助手：为工大百科条目补 images（图文配图）。后端 B / 任晟达。
-- 只更新 images 列，不动 category/question/answer/keywords。
-- 依赖：先跑 t8_ai_schema.sql（含 images 列）与 t8_kb_gongda.sql（含 INSERT）。

UPDATE kb_entries SET images='[{"url": "/kb-images/a8520811fe2db15e.jpg", "desc": "腾讯文档「工大百科」小程序首页截图，红色标注指示如何打开菜单进行搜索。"}, {"url": "/kb-images/560b19e7068da2f4.jpg", "desc": "两张「工大百科」文档界面截图，左图为首页栏目列表，右图为展开的页面目录，红字标注切换页面与展开子页面的操作。"}]' WHERE question='工大百科' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/310492cf3278e34b.jpg", "desc": "2025-2026学年第一学期校历表（含节假日标注）"}]' WHERE question='最新校历' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/ddd1cadf3ce5a4e6.jpg", "desc": "校园自助补卡终端设备照片及其触摸屏界面（自助服务系统主界面和自助补卡流程界面）。"}, {"url": "/kb-images/fd2d97c3786f76cb.jpg", "desc": "「自助机（自助补卡终端和自助圈存终端）分布情况」表格，列出各校区楼宇的自助设备类别、数量及补卡类型。"}, {"url": "/kb-images/7149e9975ec517e5.jpg", "desc": "校园3D立体地图局部，红圈标注「知新园」位置，周围为逸夫图书馆、第三教学楼及各号宿舍楼。"}]' WHERE question='校园一卡通如何补办？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/9fb251c9fe0163a8.jpg", "desc": "手机App工作台界面截图，标注如何找到本科学生证补办入口"}, {"url": "/kb-images/bbf37e62885132d9.jpg", "desc": "本科学生证补办申请表单界面截图，含填写项与办理说明"}]' WHERE question='学生证如何补办？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/34193bb6c543a22b.jpg", "desc": "校本部与通州校区之间校车（班车）发车时间表"}, {"url": "/kb-images/87cb1e83a6ddac9e.jpg", "desc": "校园三维地图局部，标注秋实广场及周边建筑"}]' WHERE question='校车（班车）时间表' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/8bff1355ecef2f75.jpg", "desc": "「网上办事大厅/一网通办」App首页截图，含我的收藏与热门服务列表，红框标注底部中间的按钮。"}, {"url": "/kb-images/9a2fb1aa594834e1.jpg", "desc": "服务大厅搜索界面截图，搜索框输入「师生亲友」，红框标注搜索结果「师生亲友入校预约申请」。"}, {"url": "/kb-images/992f9b3dd91fa748.jpg", "desc": "内网综合门户网页截图，左侧导航栏红框标注「网上办事」，右侧为用户信息面板（个人信息已打码）。"}, {"url": "/kb-images/c33ace83c1649989.jpg", "desc": "网上办事服务卡片列表截图，红框标注「师生亲友入校预约申请」卡片，展示各服务办理时限、办理量及承办部门。"}]' WHERE question='师生亲友入校预约' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/a2b29d7fa795c47d.jpg", "desc": "学生综合服务楼（Student Service Bldg.）外景照片，含思源路、学子路路口指示牌。"}, {"url": "/kb-images/0e4f6bc113d0e9f2.jpg", "desc": "快餐车（餐车）照片，蓝色车身，三名工作人员在车内售卖餐食，旁立指示牌。"}, {"url": "/kb-images/c3e877946a527cdc.jpg", "desc": "清真食堂建筑外景照片，红砖楼体，正门上方有金色「清真食堂」牌匾。"}, {"url": "/kb-images/3b27ca647967152b.jpg", "desc": "奥运餐厅外景照片，红砖建筑，门前设可乐遮阳棚展位。"}, {"url": "/kb-images/67a4cabada74c0c0.jpg", "desc": "风味餐厅/美食园（新沐兰）建筑外景，楼下挂有节能横幅。"}, {"url": "/kb-images/e511fac8d5560c71.jpg", "desc": "美食园与天天咖啡厅门面照片，右侧立有营业时间指示牌。"}]' WHERE question='食堂开放时间' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/625eb32709c3d2ce.jpg", "desc": "医院体格检查表（办游泳证用）及体检缴费治疗单实拍照片"}]' WHERE question='健康证' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/ba083c1b32fa4619.jpg", "desc": "校园地图（三维立体渲染版），标注各楼宇、宿舍、校门位置"}, {"url": "/kb-images/4ac4fc4b1b2865b4.jpg", "desc": "本部（平乐园校区）平面手绘地图，标注楼宇、操场、餐厅、校门"}, {"url": "/kb-images/3e1d8f38e1cc4ea7.jpg", "desc": "平乐园校区总平面图（矢量彩色版，文字较小不清晰）"}, {"url": "/kb-images/5a8487746c0a6ec8.jpg", "desc": "平乐园校区总平面图（带体育课程/场地标注版）"}, {"url": "/kb-images/e160a0dea4aff778.jpg", "desc": "VR校园全景入口图（经管楼中庭室内全景照片）"}, {"url": "/kb-images/c26ef4aa8334f04a.jpg", "desc": "三维校园地图局部放大图，红色箭头指向信息楼附近位置"}]' WHERE question='校园地图' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/2c89d6485bd42de4.jpg", "desc": "校园快递服务站外景，学生在取快递。"}]' WHERE question='快递地址' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/732f1a433a32a8f0.jpg", "desc": "微信小程序卡片：运动场地预约。"}, {"url": "/kb-images/dcde5614b0c34347.jpg", "desc": "田径场/足球场照片，远处学生军训列队，挂有红色标语横幅。"}, {"url": "/kb-images/572c75d7df23970a.jpg", "desc": "室外网球场照片，学生在打网球，背景为第四教学楼与艺术楼。"}, {"url": "/kb-images/19aa290e6de74185.jpg", "desc": "健身房内景照片，一排人在跑步机上跑步。"}, {"url": "/kb-images/67f0acea630cb241.jpg", "desc": "健身房收费标准表格。"}, {"url": "/kb-images/9d2311840efdf2d6.jpg", "desc": "乒乓球馆内景照片，多张红黑色乒乓球台排列。"}]' WHERE question='运动场地' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/b135e47780ca5144.jpg", "desc": "两校区（校本部、通州校区）教学上课时间表"}, {"url": "/kb-images/b0c1e27b32b24bcb.jpg", "desc": "2023-2024学年第1学期电子信息工程专业（班号230262）的个人课程表示例"}]' WHERE question='上课时间以及课表说明' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/258e3da2d69a93fb.jpg", "desc": "学号数字含义图解，以23010328为例拆解各段含义"}]' WHERE question='学号各个数字的含义' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/63ab8d3b4750f699.jpg", "desc": "校本部教学上课时间表，列出上午、下午、晚上各节次的上课时段。"}, {"url": "/kb-images/42406fe9e4d774c0.jpg", "desc": "班级“240720”2024-2025学年第1学期课表（含各星期各节次课程、教师、地点、周次）。"}, {"url": "/kb-images/479bb55cf1652f5c.jpg", "desc": "2024级新生（班级240811）2024-2025学年第1学期课程表。"}, {"url": "/kb-images/f25da5469be6771a.jpg", "desc": "2024级新生（班级240710）2024-2025学年第1学期课程表。"}]' WHERE question='2024级新生课表' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/29ce46a396dd3130.jpg", "desc": "校园防骗案例：两张微信小程序抽奖活动截图，展示虚假高额奖品与付费刷赞诱导。"}, {"url": "/kb-images/d5c65180c6ed14cc.jpg", "desc": "微信群通知截图：以奖品未落实为由将参赛者移出群聊，暗示赞助商跑路的骗局。"}, {"url": "/kb-images/06c694781635bf42.jpg", "desc": "两张微信聊天截图，一名受害者讲述“兼职PS免费教学”实为身份证贷款的诈骗亲身经历。"}]' WHERE question='校园防骗手册' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/c5a058dd01cc2f8b.jpg", "desc": "通州校区宿舍区手绘卡通鸟瞰图，标注各宿舍楼与超市位置（照片/插画）。"}, {"url": "/kb-images/61b12df652e59fa7.jpg", "desc": "宿舍上床下桌床铺与书桌近景照片，标有床位编号（照片，仅有床位号）。"}]' WHERE question='通州宿舍' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/2b89276cae3c78c4.jpg", "desc": "宿舍楼走廊翻新前后对比图（上旧下新）"}, {"url": "/kb-images/682288aedd378e51.jpg", "desc": "宿舍楼外立面翻新前后对比图（上旧下新）"}, {"url": "/kb-images/ecd97777cf32b4b4.jpg", "desc": "宿舍房间内空置的上下铺铁架床（带光斑滤镜的视频截图）"}, {"url": "/kb-images/3e424afba0e22537.jpg", "desc": "楼内新建浴室，白瓷砖墙面装有多个淋浴喷头，地面铺红毯"}, {"url": "/kb-images/921c9a382cdb2df9.jpg", "desc": "官方微博截图，配图为学校张贴的猫语禁止喂食警告牌"}, {"url": "/kb-images/27089270e3a1317a.jpg", "desc": "足球场照片，近处为球门和足球，远处为教学楼建筑"}, {"url": "/kb-images/a58def15147523f0.jpg", "desc": "学生宿舍内景照片，上下铺、蓝色柜子、书桌与生活杂物"}, {"url": "/kb-images/b9ce66b6a4dcb329.jpg", "desc": "学生宿舍内景照片，上下铺床架、书桌及生活用品"}]' WHERE question='本部宿舍' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/c2f155539535471e.jpg", "desc": "地图截图，标注从北工大西门（起）到中蓝大学生社区（终）的路线"}, {"url": "/kb-images/4c7295cbe4b12835.jpg", "desc": "中蓝校区总平面图（园区各楼栋分布及浴室、大门位置）"}, {"url": "/kb-images/a5a8cf3e3ee967aa.jpg", "desc": "学生宿舍内景照片，上下铺床、吊扇、空调及阳台门（空置状态）"}, {"url": "/kb-images/2644587ecae6d102.jpg", "desc": "学生宿舍上床下桌区域实景照片，金属床架配木色书桌和椅子"}]' WHERE question='中蓝公寓' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/ffd12391d73405d5.jpg", "desc": "2024北京工业大学百团嘉年华社团分布地图海报"}]' WHERE question='社团' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/89f9a527f4cd531f.jpg", "desc": "统一身份认证账号注册流程四步截图"}, {"url": "/kb-images/6602a289ad092290.jpg", "desc": "内网综合门户个人页面截图，红框标注网关登录按钮"}, {"url": "/kb-images/9da64d85597bf560.jpg", "desc": "校园网计费系统登录页面截图"}, {"url": "/kb-images/6f766506b3244542.jpg", "desc": "路由器背面WLAN名称和密码标签的照片，关键字段用红线标注"}]' WHERE question='校园网如何连接？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/6eb23bf3356da553.jpg", "desc": "官方网站首页截图"}, {"url": "/kb-images/2051b29bcce130f1.jpg", "desc": "计费系统登录页面截图"}, {"url": "/kb-images/16a7c25bd5bf9441.jpg", "desc": "内网综合门户网站首页截图"}, {"url": "/kb-images/76b9e8b6fe3cace7.jpg", "desc": "本科教学管理系统（正方教务）登录页面截图"}, {"url": "/kb-images/15bd39ec6837ae4b.jpg", "desc": "邮箱账号登录页面截图"}, {"url": "/kb-images/ae98e77d28a9b3b9.jpg", "desc": "图书馆网站首页截图"}, {"url": "/kb-images/fe2522ae083a9ede.jpg", "desc": "教务处网站首页顶部截图"}]' WHERE question='学校常用网址' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/1a59546efb0af912.jpg", "desc": "用户自助服务系统网页截图，演示如何删除无感知MAC地址（上网设备）"}, {"url": "/kb-images/051ea5c529abb6a4.jpg", "desc": "安卓手机WLAN设置界面截图，标注在此查看MAC地址辨别登录设备"}, {"url": "/kb-images/7190d46ea4cdbc7b.jpg", "desc": "Windows电脑网络WLAN属性界面截图，标注电脑端MAC地址查看位置"}, {"url": "/kb-images/e56aa722fdb696bd.jpg", "desc": "安卓手机WLAN列表界面截图，标注删除后重新打开WLAN会显示需要登录"}]' WHERE question='校园网如何切换账号？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/f606b8443ec44aaa.jpg", "desc": "门户首页截图，标注点击“我的邮箱”并点“开户”申请邮箱"}, {"url": "/kb-images/16d9cda03ae1bb57.jpg", "desc": "邮箱开户填写表单弹窗截图（以示例信息演示）"}, {"url": "/kb-images/2b5a3357524077bc.jpg", "desc": "邮箱开户成功后已绑定邮箱的弹窗截图"}]' WHERE question='如何申请工大邮箱？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/646b51b59d87f226.jpg", "desc": "本科教学管理系统截图，展示在“信息查询”下拉菜单中点击“班级课表查询”的步骤"}, {"url": "/kb-images/341adc25d552c8f7.jpg", "desc": "“班级课表查询”页面截图，展示学年、学期、学院、专业、班级等筛选条件（尚未查询）"}, {"url": "/kb-images/e5f3d2da9b8fd41a.jpg", "desc": "“班级课表查询”页面截图，以城乡规划专业为例查询出不同班级的课表列表"}]' WHERE question='如何查每个专业的课表' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/9532a86813e4a615.jpg", "desc": "各学部（院）教务科办公电话与邮箱地址一览表"}]' WHERE question='常用电话' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/d3fff4729cca84c3.jpg", "desc": "WebVPN门户业务系统与业务办理入口页面截图"}, {"url": "/kb-images/dba84c475244aedd.jpg", "desc": "统一身份认证账号登录界面示意图，标注点击【账号信息】"}, {"url": "/kb-images/ef3f5377895ca8ec.jpg", "desc": "MotionPro OTP令牌APP登录配置及一次性密码获取界面示意图"}, {"url": "/kb-images/25e7d641d0c05b1b.jpg", "desc": "手机VPN客户端（Array SSL VPN）三个界面截图：网关配置、认证登录、资源列表，标注OTP密码填写位置。"}, {"url": "/kb-images/42fde0913acb2c7e.jpg", "desc": "双因素认证VPN使用方法说明文档，含电脑端网页登录、MotionPro客户端连接界面截图。"}]' WHERE question='校园网VPN指南' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/2f3825bfefa3e3c1.jpg", "desc": "校园一卡通学生卡照片（示例卡，信息为虚构样例）。"}, {"url": "/kb-images/7283175ece2030b0.jpg", "desc": "微信/小程序中的北京工业大学电子校园卡界面截图，显示余额及扫一扫、校园码入口。"}]' WHERE question='一卡通常见问题' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/d4b104be5b9e506e.jpg", "desc": "软件正版化平台官网首页截图，含正版软件下载入口与联系方式"}, {"url": "/kb-images/188b252c9747bc1c.jpg", "desc": "软件正版化平台“使用技巧”页面截图，展示办公软件专区Office视频教程列表"}, {"url": "/kb-images/c2077e54baec957f.jpg", "desc": "软件正版化平台“常见问题”页面截图，列出Office激活报错等问题的原因解答"}]' WHERE question='正版软件下载及使用' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/4a66d6ccdc52ab16.jpg", "desc": "本科教学管理系统登录页面截图（教务系统登录说明）"}, {"url": "/kb-images/d4fa4ced1b2bbd8f.jpg", "desc": "教务系统首页截图，红色标注提示点击“信息查询”菜单"}, {"url": "/kb-images/232bb09570c0cc63.jpg", "desc": "教务系统“信息查询”下拉菜单截图，红色标注提示点击“查询空闲教室”"}, {"url": "/kb-images/508e100bd1750308.jpg", "desc": "教务系统“查询空闲教室”查询界面截图，红色标注说明可查看各教学楼空教室"}]' WHERE question='如何查询空教室？' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/c35df142f1a2d327.jpg", "desc": "本科生成绩证明自助打印终端设备现场照片"}]' WHERE question='打印成绩单' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/f7dd7a1b6e263d3a.jpg", "desc": "第一、第二教学楼外景照片"}, {"url": "/kb-images/773085c9347a4ff0.jpg", "desc": "第三教学楼外景照片"}, {"url": "/kb-images/2417e7056eba07f1.jpg", "desc": "第四教学楼外景照片"}, {"url": "/kb-images/b63f4bed3ba928c7.jpg", "desc": "图书馆（新馆）建筑夜景鸟瞰效果图"}, {"url": "/kb-images/f75b90297cd58734.jpg", "desc": "图书馆内部中庭与楼层挑空、阶梯座位实景照片"}, {"url": "/kb-images/6c5fcf1e3c33a58c.jpg", "desc": "图书馆各区域开馆时间表"}, {"url": "/kb-images/06e68e2d7e3cd2ef.jpg", "desc": "逸夫图书馆B1层平面布局图"}, {"url": "/kb-images/6908764644e09d80.jpg", "desc": "逸夫图书馆一层平面布局图"}, {"url": "/kb-images/8cb35b8635629da5.jpg", "desc": "逸夫图书馆二层平面布局图（含中文社科分区）"}, {"url": "/kb-images/0f6fbba3e3029258.jpg", "desc": "逸夫图书馆三层布局图（藏书分区平面图）"}]' WHERE question='自习室和图书馆' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/52c0380ad47dc2a0.jpg", "desc": "全国大学英语四、六级考试（CET）报名网站首页截图。"}]' WHERE question='四六级' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/ebf7ec8bf810864b.jpg", "desc": "学籍管理规定第十四条截图，说明学分通过率与加权平均分的计算方法（关键部分绿色高亮）。"}, {"url": "/kb-images/73aa6bfeb392f5e6.jpg", "desc": "学籍管理规定关于补考、重修及成绩记载的条款截图（第二至第七项，多处绿色高亮）。"}, {"url": "/kb-images/ee605ba309b102d1.jpg", "desc": "本校GPA绩点分数段划分表及GPA计算公式。"}]' WHERE question='加权和GPA' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/12f7a274abdf5721.jpg", "desc": "信息学部转专业接收条件表（计算机科学与技术、信息安全、物联网工程专业）。"}]' WHERE question='转专业' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/bf61b3a3aa3489ef.jpg", "desc": "计算机科学与技术专业2022版本科指导性教学计划进程表一（完整课程学分学时表）。"}, {"url": "/kb-images/89e3a1696136dbf0.jpg", "desc": "计算机科学与技术专业2022版教学计划进程表（同107）的红色批注讲解版，讲解如何读表。"}, {"url": "/kb-images/0d139e2924594c6d.jpg", "desc": "教学计划课程表片段，列出各课程编码、名称、学分、学时分配及各学期计划学分"}, {"url": "/kb-images/8a687e704abef931.jpg", "desc": "培养方案学分结构汇总表，按专业教育/通识教育分类列出各类课程学分、学时及各学期分布，并含理论、实践、总计合计行"}, {"url": "/kb-images/9b3ed1c68012b4e7.jpg", "desc": "学分结构汇总表的放大片段，突出显示专业教育与通识教育各类课程的学分数"}, {"url": "/kb-images/7140982649ec7f3d.jpg", "desc": "本科教学管理系统截图，左侧“信息查询”菜单展开并高亮“学生学业情况查询”，右侧显示某学生课程修读情况树状统计"}]' WHERE question='读懂教学计划' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/e23b81b0e67dbde0.jpg", "desc": "两张学位/辅修证书样张对比图，左为辅修学士学位（在主修学士学位证书中予以注明），右为辅修结业证书"}, {"url": "/kb-images/ff215684870fcf85.jpg", "desc": "2021级全校辅修专业报名特殊要求表，列出各学院开设专业、开设形式、报名特殊要求及测试时间地点"}, {"url": "/kb-images/2c9ebb51fbea7e13.jpg", "desc": "本科教学管理系统登录页面截图，含用户登录框及账号密码说明"}, {"url": "/kb-images/fa8748a546bf01b2.jpg", "desc": "教务处网站截图，导航到“专业建设-教学计划”，页面显示辅修结业计划列表及左侧栏辅修相关计划入口"}, {"url": "/kb-images/af5fec7e9349fd7b.jpg", "desc": "2021级全校专业所属专业类、授予学位情况一览表，按学部列出专业名称、所属专业类及授予学位"}]' WHERE question='辅修和双学位' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/6648bd141d7ac410.jpg", "desc": "境外交流项目分类说明表，比较长期交流项目与短期交流项目的项目情况和资助政策条件"}, {"url": "/kb-images/abf57098a52c4709.jpg", "desc": "2023年暑期境外线下研学项目一览表，列出各项目编号、名称、时间、课程方向及内容概要"}, {"url": "/kb-images/7fff07bdbc09412a.jpg", "desc": "2023年秋季学期学生境外交流项目一览表（第二批），列出各合作院校的国家、交流形式、免费/自费名额及可接收专业"}, {"url": "/kb-images/4b670d6c61d4a34c.jpg", "desc": "2023牛津展望暑期访学项目介绍页（项目简介与报名信息）"}, {"url": "/kb-images/d9d6392d979ed77e.jpg", "desc": "长期境外交流项目手册中美国南加州大学（USC）本硕衔接项目介绍页"}]' WHERE question='国际交流项目' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/5c52e5bc08d955f5.jpg", "desc": "第二课堂管理办法第四章学分设置标准（第十条）条文"}, {"url": "/kb-images/91841707188a687a.jpg", "desc": "第二课堂必选课程和学分设置附录表格"}, {"url": "/kb-images/a523f8f4718d9955.jpg", "desc": "学习通App“我的单位”设置界面截图，含添加第二课堂单位的操作提示"}, {"url": "/kb-images/658982dcd6032e49.jpg", "desc": "学习通App应用中心（北京工业大学第二课堂学生端）界面截图，标注查看第二课堂成绩单入口"}]' WHERE question='第二课堂' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/81b843558d636403.jpg", "desc": "2026届各学院保研率统计表（制作：@工大喵）"}]' WHERE question='保研' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/6f23506d57810183.jpg", "desc": "《北京工业大学学生生活补贴发放办法》文字说明（3.4其他事务）"}]' WHERE question='生活补贴' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/b4b9d6bad4726abd.jpg", "desc": "心理中心走廊照片，墙边有心理学书架、书籍、绿植和相框（照片，无文字信息）"}, {"url": "/kb-images/8ae71208a1150c5b.jpg", "desc": "心理中心路线图（楼层平面示意图）"}]' WHERE question='心理咨询' AND source='工大百科(学生整理)';
UPDATE kb_entries SET images='[{"url": "/kb-images/fbb353a99f8cdf3b.jpg", "desc": "公费医疗管理办法第二条“享受公费医疗待遇的人员范围”条文"}, {"url": "/kb-images/a85809b04ae8a867.jpg", "desc": "微信搜索“北京工业大学医院”公众号的结果页截图，红框标注“线上挂号”入口"}, {"url": "/kb-images/21c8896d6c8500a1.jpg", "desc": "医院公众号首页截图，红框标注学生当日挂号和预约挂号入口"}, {"url": "/kb-images/da0c1d7350e49839.jpg", "desc": "微信搜索“友谊医院”的搜索结果页面截图，展示北京友谊医院的信息卡片，标注操作步骤一。"}, {"url": "/kb-images/bd3636e790cbda8e.jpg", "desc": "北京友谊医院“院区选择”页面截图，列出三个院区及地址，标注操作步骤二。"}, {"url": "/kb-images/2c9f1cabb9fecc4f.jpg", "desc": "北京友谊医院患者服务小程序首页截图，红框标出“预约挂号”入口，标注操作步骤三。"}]' WHERE question='校医院和公费医疗' AND source='工大百科(学生整理)';
